import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'components/uploader/index': 'src/components/uploader/index.ts',
    'components/picker/index': 'src/components/picker/index.ts',
    'components/toaster/index': 'src/components/toaster/index.ts',
    'components/timeline/index': 'src/components/timeline/index.ts',
    'components/tabbar/index': 'src/components/tabbar/index.ts',
    'components/steps/index': 'src/components/steps/index.ts',
    'components/notice-bar/index': 'src/components/notice-bar/index.ts',
    'components/navbar/index': 'src/components/navbar/index.ts',
    'components/menu/index': 'src/components/menu/index.ts',
    'components/input-otp/index': 'src/components/input-otp/index.ts',
    'components/image/index': 'src/components/image/index.ts',
    'components/collapse/index': 'src/components/collapse/index.ts',
    'components/card/index': 'src/components/card/index.ts',
    'components/tour/index': 'src/components/tour/index.ts',
    'components/swipe-action/index': 'src/components/swipe-action/index.ts',
    'components/tabs/index': 'src/components/tabs/index.ts',
    'components/textarea/index': 'src/components/textarea/index.ts',
    'components/stepper/index': 'src/components/stepper/index.ts',
    'components/calendar/index': 'src/components/calendar/index.ts',
    'components/avatar/index': 'src/components/avatar/index.ts',
    'components/action-sheet/index': 'src/components/action-sheet/index.ts',
    'components/drawer/index': 'src/components/drawer/index.ts',
    'components/selectbox/index': 'src/components/selectbox/index.ts',
    'components/listbox/index': 'src/components/listbox/index.ts',
    'components/skeleton/index': 'src/components/skeleton/index.ts',
    'components/pickbox/index': 'src/components/pickbox/index.ts',
    'components/scrollbox/index': 'src/components/scrollbox/index.ts',
    'components/popup/index': 'src/components/popup/index.ts',
    index: 'src/index.ts',
    'components/button/index': 'src/components/button/index.ts',
    'components/checkbox/index': 'src/components/checkbox/index.ts',
    'components/field/index': 'src/components/field/index.ts',
    'components/input/index': 'src/components/input/index.ts',
    'components/radio/index': 'src/components/radio/index.ts',
    'components/switch/index': 'src/components/switch/index.ts',
  },
  external: [/^@srcube-ui\/styles(\/.*)?$/, 'react', 'react-dom', 'react-aria-components', 'tailwind-variants'],
  skipNodeModulesBundle: true,
  inlineOnly: false,
  dts: true,
  sourcemap: false,
  fixedExtension: false,
});
