import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'components/drawer/index': 'src/components/drawer/index.ts',
    'components/selectbox/index': 'src/components/selectbox/index.ts',
    'components/listbox/index': 'src/components/listbox/index.ts',
    'components/skeleton/index': 'src/components/skeleton/index.ts',
    'components/pickbox/index': 'src/components/pickbox/index.ts',
    'components/scrollbox/index': 'src/components/scrollbox/index.ts',
    'components/popup/index': 'src/components/popup/index.ts',
    index: 'src/index.ts',
    'components/button/index': 'src/components/button/index.ts',
    'components/checkbox/index': 'src/components/checkbox/index.ts',
    'components/radio/index': 'src/components/radio/index.ts',
    'components/switch/index': 'src/components/switch/index.ts',
    'components/field/index': 'src/components/field/index.ts',
    'components/input/index': 'src/components/input/index.ts',
    'components/field/index': 'src/components/field/index.ts',
    'components/checkbox/index': 'src/components/checkbox/index.ts',
    'components/radio/index': 'src/components/radio/index.ts',
    'components/switch/index': 'src/components/switch/index.ts',
  },
  external: [/^@srcube-ui\/styles(\/.*)?$/, 'react', 'react-dom', 'react-aria-components', 'tailwind-variants'],
  skipNodeModulesBundle: true,
  inlineOnly: false,
  dts: true,
  sourcemap: false,
  fixedExtension: false,
});
